Example 2-1. Build a list of Unicode code points from a string

In [2]:
symbols = "$¢£¥€¤"
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

codes

[36, 162, 163, 165, 8364, 164]

Example 2-2. Build a list of Unicode code points from a string, using a listcomp

In [3]:
symbols = "$¢£¥€¤"
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

Example 2-3. The same list built by a listcomp and a map/filter composition

In [4]:
symbols = "$¢£¥€¤"
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)

beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
print(beyond_ascii)

[162, 163, 165, 8364, 164]
[162, 163, 165, 8364, 164]


Example 2-4. Cartesian product using a list comprehension

In [7]:
colors = ["black", "white"]
sizes = ["S", "M", "L"]
tshirts = [(color, size) for color in colors for size in sizes]
print(tshirts)
print("---")
for color in colors:
    for size in sizes:
        print((color, size))
print("---")
tshirts = [(color, size) for size in sizes for color in colors]
print(tshirts)

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
---
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')
---
[('black', 'S'), ('white', 'S'), ('black', 'M'), ('white', 'M'), ('black', 'L'), ('white', 'L')]


Example 2-5. Initializing a tuple and an array from a generator expression

In [8]:
symbols = "$¢£¥€¤"
print(tuple(ord(symbol) for symbol in symbols))
import array

array.array("I", (ord(symbol) for symbol in symbols))

(36, 162, 163, 165, 8364, 164)


array('I', [36, 162, 163, 165, 8364, 164])

Example 2-6. Cartesian product in a generator expression

In [9]:
colors = ["black", "white"]
sizes = ["S", "M", "L"]
for tshirt in (f"{c} {s}" for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


Example 2-7. Tuples used as records

In [13]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ("Tokyo", 2003, 32_450, 0.66, 8014)
traveler_ids = [("USA", "31195855"), ("BRA", "CE342567"), ("ESP", "XDA2050856")]
for passport in sorted(traveler_ids):
    print("%s/%s" % passport)
print("----")
for country, _ in traveler_ids:
    print(country)

BRA/CE342567
ESP/XDA2050856
USA/31195855
----
USA
BRA
ESP


Example 2-8. Unpacking nested tuples to access the longitude

In [15]:
metro_areas = [
    ("Tokyo", "JP", 36.933, (35.689722, 139.691667)),
    ("Delhi NCR", "IN", 21.935, (28.613889, 77.208889)),
    ("Mexico City", "MX", 20.142, (19.433333, -99.133333)),
    ("New York-Newark", "US", 20.104, (40.808611, -74.020386)),
    ("São Paulo", "BR", 19.649, (-23.547778, -46.635833)),
]


def main():
    print(f"{'':15} | {'latitude':>9} | {'longitude':>9}")
    for name, _, _, (lat, lon) in metro_areas:
        if lon <= 0:
            print(f"{name:15} | {lat:9.4f} | {lon:9.4f}")


main()

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


Example 2-9. Method from an imaginary *Robot* class

In [16]:
def handle_command(self, message):
    match message:
        case ["Beeper", frequency, times]:
            self.beep(times, frequency)
        case ["Neck", angle]:
            self.rotate_neck(angle)
        case ["LED", ident, intensity]:
            self.leds[ident].set_brightness(ident, intensity)
        case ["LED", ident, red, green, blue]:
            self.leds[ident].set_color(ident, red, green, blue)
        case _:
            raise Exception(message)

Example 2-10. Destructuring nested tuples

In [19]:
metro_areas = [
    ("Tokyo", "JP", 36.933, (35.689722, 139.691667)),
    ("Delhi NCR", "IN", 21.935, (28.613889, 77.208889)),
    ("Mexico City", "MX", 20.142, (19.433333, -99.133333)),
    ("New York-Newark", "US", 20.104, (40.808611, -74.020386)),
    ("São Paulo", "BR", 19.649, (-23.547778, -46.635833)),
]


def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for record in metro_areas:
        match record:
            case [name, _, _, (lat, lon)] if lon <= 0:
                print(f"{name:15} | {lat:9.4f} | {lon:9.4f}")


main()

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


Example 2-13. Line items ffrom a flat-file invoice

In [3]:
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                 $17.50      3  $52.50
1489  6mm Tactile Switch x20            $4.95       2  $9.90
1510  Panavise Jr. - PV-201             $28.00      1  $28.00
1601  PiTFT Mini Kit 320x240            $34.95      1  $34.95
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split("\n")[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

$17.50       Pimoroni PiBrella                 
$4.95        6mm Tactile Switch x20            
$28.00       Panavise Jr. - PV-201             
$34.95       PiTFT Mini Kit 320x240            
 


Example 2-14. A list with three lists of length 3 can represent a tic-tac-toe board

In [5]:
board = [["_"] * 3 for i in range(3)]
print(board)
board[1][2] = "X"
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


Example 2-15. A list with three references to the same list is useless

In [6]:
weird_board = [["_"] * 3] * 3
print(weird_board)
weird_board[1][2] = "O"
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

Example 2-19. Creating, saving, and loading a large array of floats

In [12]:
from array import array
from random import random

floats = array("d", (random() for i in range(10**7)))
print(floats[-1])
fp = open("floats.bin", "wb")
floats.tofile(fp)
fp.close()
floats2 = array("d")
fp = open("floats.bin", "rb")
floats2.fromfile(fp, 10**7)
fp.close()
print(floats2[-1])
floats2 == floats

0.25479517220125947
0.25479517220125947


True

Example 2-20. Handling 6 bytes of memory as 1x6, 2x3, and 3x2 views

In [13]:
from array import array

octets = array("B", range(6))
m1 = memoryview(octets)
print(m1.tolist())
m2 = m1.cast("B", [2, 3])
print(m2.tolist())
m3 = m1.cast("B", [3, 2])
print(m3.tolist())
m2[1, 1] = 22
m3[1, 1] = 33
octets

[0, 1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5]]
[[0, 1], [2, 3], [4, 5]]


array('B', [0, 1, 2, 33, 22, 5])

Example 2-21. Changing the value of a 16-bit integer array item by poking one of its bytes

In [22]:
numbers = array("h", [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))
print(memv[0])
memv_oct = memv.cast("B")
memv_oct.tolist()
memv_oct[5] = 4
numbers

5
-2


array('h', [-2, -1, 1024, 1, 2])

Example 2-22. Basic operations with rows and columns in a numpy.ndarray

In [3]:
import numpy as np

a = np.arange(12)
print(a)
print(type(a))
print(a.shape)
a.shape = 3, 4
print(a)
print(a.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Example 2-23. Working with a deque

In [8]:
from collections import deque

dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [9]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [10]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [11]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [12]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [13]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)